### ISSUE TITLE
Error: Text strings must be rendered within a <Text> component.

### ISSUE THREAD

**Issue by shaneosullivan** [pvoznyuk/react-live-clock#276] opened 2023-07-26 13:40 UTC
When using the `<Clock>` component in an Expo app and Expo Router (may not be the issue), I get the error that text strings must be rendered using a Text component

Expo SDK version: "~49.0.5"
React Native version: "0.72.3"
React Live Clock version: "^6.1.14"

## Code 
```
import { Text, View } from "react-native";

import Clock from "react-live-clock";

export default function ClockPage() {
  return (
    <View>
      <Text>Clock page</Text>
      <Clock format={"HH:mm:ss"} ticking={true} timezone={"US/Pacific"} />
    </View>
  );
}

```

## Error output
<img width="632" alt="Screenshot 2023-07-26 at 22 37 03" src="https://github.com/pvoznyuk/react-live-clock/assets/49378/66046e10-7e54-42a0-a9d9-f2bae6dc6aa9">

**Comment by anthony0030** [comment] 2023-07-26 13:54
Hello! is tis a duplicate of #21 ?

Try adding

```JSX
element={Text}
```

Like this


```JSX
import { Text, View } from "react-native";

import Clock from "react-live-clock";

export default function ClockPage() {
  return (
    <View>
      <Text>Clock page</Text>
      <Clock element={Text} format={"HH:mm:ss"} ticking={true} timezone={"US/Pacific"} />
    </View>
  );
}
```

**Comment by shaneosullivan** [comment] 2023-07-26 13:57
> Hello! is tis a duplicate of #21 ?

Ah yes it is, apologies I don't know how I missed that.  Your fix worked thanks.  Perhaps it would be worth adding to the default Readme?

**Closed** 2023-07-27 06:19 UTC

**Comment by anthony0030** [comment] 2023-07-27 06:26
@shaneosullivan Good sugetion! I have added this code to the read me file. Thankyou for making this project a bit better.
