### ISSUE TITLE
Invariant Violation: Text strings must be rendered within a <Text> component. 

### ISSUE THREAD

**Issue by talha2k** [pvoznyuk/react-live-clock#21] opened 2019-01-07 12:22 UTC
This is my render function:

```
render() {
    return (
      <View style={styles.container}>
        <Text style={styles.text}>Hello World!
          <Clock format={'HH:mm:ss'} ticking={true} timezone={'US/Pacific'} />
        </Text>
        
      </View>
    );
  }
```
There is an error coming up: 

Invariant Violation: Text strings must be rendered within a <Text> component. 

Moving <Clock> outside <Text> and even <View> doesn't fix the problem.

**Comment by anthony0030** [comment] 2020-01-28 16:27
Are you using react native?

**Comment by avinashsahoo** [comment] 2022-01-25 19:22
Yes, I'm facing same issue

**Comment by anthony0030** [comment] 2022-01-26 07:22
Are you using react native?

**Comment by avinashsahoo** [comment] 2022-01-26 13:02
Yes, I'm using react native.

**Comment by anthony0030** [comment] 2022-01-26 15:27
Using ```"react-live-clock": "5.6.0"``` try the following:

```JSX
   <Clock element={Text} />
```

**Comment by anthony0030** [comment] 2022-01-27 07:18
Good morning @avinashsahoo and @talha2k,
Did ```"react-live-clock": "5.6.0"``` fix your problem?
If I get no negative response by Friday 18:00 GMT+2 I will close this issue.
I hope you have a great day :)

**Comment by avinashsahoo** [comment] 2022-01-27 08:43
It didn't work. 
Anyway, i've developed my own component for timer. Thanks.

**Comment by ReeceKenney** [comment] 2023-01-06 09:34
I know this was closed around one year ago, but just following up to say that this worked for me. Thanks Anthony!

**Comment by ReeceKenney** [comment] 2023-01-15 13:10
Hi Anthony, so sorry for the slow response! Can I ask where you want me to put this log? As a guess, I put it in lob/component.js and it output 'object'

**Comment by anthony0030** [comment] 2023-01-15 13:19
Perfect! I will try and fix the prop validation tomorrow! I hope you had a great weekend!

**Comment by anthony0030** [comment] 2023-01-23 17:44
Hi Reece, Sorry for the delay. I have been sick this last week.
this problem should be fixed on react-live-clock@6.1.3

**Comment by ReeceKenney** [comment] 2023-01-26 20:58
No problem at all Anthony, thanks so much for your efforts. I just tried it and can confirm the error has disappeared. All the best!

**Comment by ganholete** [comment] 2023-02-07 11:49
Hey guys! I am on version 6.1.6 and I remain with the non-existent property annoyance in react-native:

![image](https://user-images.githubusercontent.com/16022083/217237056-9401e426-f3e3-43d2-9af7-b9ed5f75cd5d.png)

**Comment by anthony0030** [comment] 2023-02-07 16:43
Hi @ganholete, 
I don't know TypeScript, but it seems that I was missing the thingies.
I added them, so please update to ```6.1.9``` and let me know.

**Comment by ganholete** [comment] 2023-02-09 11:34
The error keeps appearing because of the typescript, but it's just annoying, because it works correctly.

**Comment by anthony0030** [comment] 2023-02-09 11:39
@ganholete do you still get this error on version ```6.1.9```?

**Comment by anthony0030** [comment] 2023-02-09 11:44
@SamChou19815 you contributed to this project via PR #31 Could you please help by checking that I have updated the definitions correctly? :)

**Comment by ganholete** [comment] 2023-02-09 11:45
@anthony0030 yep
![image](https://user-images.githubusercontent.com/16022083/217804088-688a00de-8e14-435f-8336-dadbe4fc79bb.png)
![image](https://user-images.githubusercontent.com/16022083/217804183-c02b1b8f-1fea-4908-b735-dc3678993e3f.png)

**Comment by anthony0030** [comment] 2023-02-09 13:37
What is the type of ```Text```?  if you give me that info I can add it in.
I know how annoying false positive errors are.

**Comment by ganholete** [comment] 2023-02-09 19:08
![image](https://user-images.githubusercontent.com/16022083/217913349-e953bd58-c73b-431b-af00-83346bc0516e.png)
Apparently it worked as expected and there are no type errors, but I haven't tested it deeply

**Closed** 2023-02-10 15:11 UTC

**Comment by anthony0030** [comment] 2023-02-10 15:12
Please try ```react-live-clock@6.1.10``` and tell me if the problem is fixed.

**Comment by ganholete** [comment] 2023-02-10 16:56
![image](https://user-images.githubusercontent.com/16022083/218150279-fc67d11a-f294-4986-9d10-479b121aa2e2.png)
It doesn't work, even when I come back with my code.

**Comment by anthony0030** [comment] 2023-02-13 07:18
Please try ```react-live-clock@6.1.11```

**Comment by ganholete** [comment] 2023-02-13 14:03
Like a charm, you are the best!
![image](https://user-images.githubusercontent.com/16022083/218478587-a46cb1c0-3335-4ea1-bdf5-42d6223fe71f.png)

**Comment by anthony0030** [comment] 2023-02-13 14:56
Cool @ganholete happy to see that you aren't getting that annoying error!
Have a Great week!
