### ISSUE TITLE
resolve react-moment?

### ISSUE THREAD

**Issue by Nolanws1** [pvoznyuk/react-live-clock#77] opened 2021-01-12 01:43 UTC
Is there any trick to this? 

```
./node_modules/react-live-clock/lib/Component.js
Module not found: Can't resolve 'react-moment' in '/Users/nolan/clock/node_modules/react-live-clock/lib'
```

I'm following documentation/ youtube and seem to keep runing into this...

**Comment by Nolanws1** [comment] 2021-01-12 01:46
I'm so sorry. I c&p the wrong console error this this the error I am referring to...

`./node_modules/react-live-clock/lib/Component.js
Module not found: Can't resolve 'moment-timezone' in '/Users/nolan/scratch-react/node_modules/react-live-clock/lib'`

**Comment by anthony0030** [comment] 2021-01-12 10:16
You need to have this module installed ```yarn add moment-timezone``` or ```npm install moment-timezone```

**Comment by damiangreen** [comment] 2022-07-20 14:45
Ye this is a bug it ought to be in dependencies , not peer dependencies

**Comment by anthony0030** [comment] 2022-07-21 06:24
it was to fix a problem with the build size ( #40 ).
the dependencies go in the peer dependencies so that you can have the version you want and the build will be lighter.

**Comment by damiangreen** [comment] 2022-08-01 19:05
it means we now have moment and moment-timezone though...

**Comment by anthony0030** [comment] 2022-08-02 06:21
I think the problem is that some of the peer deps are locked down too tight.
This is the only package I have ever maintained, and I am doing my best.

@Nolanws1, @damiangreen could you please take a look at
https://nodejs.org/en/blog/npm/peer-dependencies

I moved them to peer deps so the package was smaller on build, I don't know why they are not automatically installing or at least giving an error telling you to install

**Comment by damiangreen** [comment] 2022-11-03 10:42
It also appears it depends on `@types/moment-timezone`
This package is marked as unneeded by PnPm

**Comment by anthony0030** [comment] 2022-11-08 16:24
@damiangreen  what do you suggest I do?

**Comment by anthony0030** [comment] 2022-11-22 11:15
I made some changes I hope it helps

**Closed by anthony0030** 2022-11-22 11:15 UTC
